### ISSUE TITLE
Missing dependencies for fts-rest-cli

### ISSUE THREAD

**Issue by daikema** [brucellino/ansible-umd#1]
When attempting to install the UMD-packaged version of `fts-rest-cli` into singularity container (found in [this repo](https://github.com/idia-astro/fts-client-container) I hit upon some missing dependencies when attempting to run the client.

```
fts-rest-transfer-submit --help
Traceback (most recent call last):
  File "/bin/fts-rest-transfer-submit", line 2, in <module>
    from fts3.cli import JobSubmitter
  File "/usr/lib/python2.7/site-packages/fts3/__init__.py", line 1, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

This first error was resolved by adding the `python-setuptools` package to the container build def.  
Following that a second error was also encountered:

```
fts-rest-transfer-submit --help
Traceback (most recent call last):
  File "/bin/fts-rest-transfer-submit", line 2, in <module>
    from fts3.cli import JobSubmitter
  File "/usr/lib/python2.7/site-packages/fts3/cli/__init__.py", line
18, in <module>
    from banning import Banning
  File "/usr/lib/python2.7/site-packages/fts3/cli/banning.py", line
18, in <module>
    from base import Base
  File "/usr/lib/python2.7/site-packages/fts3/cli/base.py", line 25, in <module>
    from fts3.rest.client import Context
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/__init__.py",
line 19, in <module>
    from context import Context
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/context.py",
line 36, in <module>
    from request import Request
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/request.py",
line 20, in <module>
    import requests
  File "/users/aikema/.local/lib/python2.7/site-packages/requests/__init__.py",
line 97, in <module>
    from . import utils
  File "/users/aikema/.local/lib/python2.7/site-packages/requests/utils.py",
line 24, in <module>
    from . import certs
  File "/users/aikema/.local/lib/python2.7/site-packages/requests/certs.py",
line 15, in <module>
    from certifi import where
ImportError: No module named certifi
```

I didn't notice any package available via `yum` which would resolve this missing dependency issue so for the moment I'm installing this via `pip` in the container def file.

**Comment by brucellino** [comment]
Thanks @daikema ! I'll take a look and see if I can reproduce and fix. This fix will probably come in in a separate role or channel but you'll also be notified her.

**Comment by daikema** [comment]
I discovered that the requests package was being pulled from my home directory as when I ran as another user I hit the following error:
```
Traceback (most recent call last):
  File "/bin/fts-rest-transfer-list", line 2, in <module>
    from fts3.cli import JobLister
  File "/usr/lib/python2.7/site-packages/fts3/cli/__init__.py", line 18, in <module>
    from banning import Banning
  File "/usr/lib/python2.7/site-packages/fts3/cli/banning.py", line 18, in <module>
    from base import Base
  File "/usr/lib/python2.7/site-packages/fts3/cli/base.py", line 25, in <module>
    from fts3.rest.client import Context
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/__init__.py", line 19, in <module>
    from context import Context
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/context.py", line 36, in <module>
    from request import Request
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/request.py", line 20, in <module>
    import requests
ImportError: No module named requests
```

Installing the `python2-requests` package resolved this issue.
